name: provider_demo
description: A podcast app built with flutter and Listen note API (Podcast
Search & Directory API).


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  http: ^0.12.2
  get_it: ^5.0.3
  google_fonts: ^1.1.2
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true


dependecy_overrides:
  collection: ^1.14.12